name: SSH Connect_OSTAD
run-name: ${{github.actor}} is running ${{github.action_path}}
on:
  push:
    branches:
      - main

jobs:
  ssh-test:
    runs-on: ubuntu-latest

    steps:
      - name: Beforessh
        run: |
          echo ${{ vars.STUDENT }}
          ip addr
  

    
